[project]
name = "pyspark-ds-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "authlib>=1.6.0",
    "bcrypt == 4.3.0",
    "cryptography>=45.0.4",
    "faker>=37.4.0",
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pandas>=2.2.3",
    "passlib==1.7.4",
    "pyaml>=25.1.0",
    "pyjwt>=2.10.1",
    "pyspark<=3.5.5",
    "python-dotenv>=1.1.0",
    "python-multipart>=0.0.20",
    "requests>=2.32.3",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8-pyproject>=1.2.3",
    "isort>=6.0.1",
    "pytest-sugar>=1.0.0",
]

[tool.flake8]
ignore = ['E231', 'E241']
per-file-ignores = ['__init__.py:F401']
max-line-length = 128
count = true
exclude = [".venv"]
