version: "3.8"
services:

    # Oracle service (label used to access the service container)
    oracle:

      # Docker Hub image (feel free to change the tag "latest" to any other available one)
      image: gvenzl/oracle-xe:latest
      container_name: oracle

      # Provide passwords and other environment variables to container
      environment:
        APP_USER: oracle
        APP_USER_PASSWORD: Oracle_2023
        ORACLE_DATABASE: oracledb
        ORACLE_PASSWORD: Oracle_2023

      # Forward Oracle port
      ports:
        - "1521:1521"
        - "5050:5050"

      # Provide healthcheck script options for startup
      healthcheck:
        test: healthcheck.sh
        interval: 10s
        timeout: 5s
        retries: 10