[project]
name = "pyspark-config"
version = "0.1.0"
description = "PySpark configuration examples"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyspark==3.5.0",
    "findspark~=2.0.1",
    "jproperties~=2.1.1",
]

[dependency-groups]
dev = [
    "pytest>=7.4.2",
]
docs = [
    "mkdocs-material>=9.5",
    "mkdocs-include-markdown-plugin>=6.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
