"""Generate XML data from an XSD schema using xmlschema.encode.

Reuses the orders.xsd generated by xsd_to_xml_2.py (or creates it),
then builds 1000 Order dicts and encodes them via xmlschema into
a valid XML file.
"""

import os
import random
import sys
import xml.etree.ElementTree as ET
from datetime import date, timedelta
from pathlib import Path

import xmlschema

from spark_xml.schema.xsd.generate.xsd_to_xml_2 import ORDERS_XSD, generate_xsd_file

os.environ["JAVA_HOME"] = os.environ.get("JAVA_HOME_17", os.environ.get("JAVA_HOME", ""))
os.environ["PYSPARK_PYTHON"] = sys.executable


def random_date() -> str:
    start = date(2024, 1, 1)
    delta = random.randint(0, 730)
    return str(start + timedelta(days=delta))


def random_item() -> dict:
    return {
        "ProductName": "".join(random.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=3))
        + "-"
        + str(random.randint(100, 999)),
        "Quantity": random.randint(1, 50),
        "UnitPrice": round(random.uniform(5.0, 500.0), 2),
    }


def random_order(order_id: int) -> dict:
    """Build a dict that matches the Orders/Order XSD structure."""
    items = [random_item() for _ in range(random.randint(1, 5))]
    total = sum(it["Quantity"] * it["UnitPrice"] for it in items)
    return {
        "OrderID": f"ORD-{order_id:04d}",
        "CustomerName": f"Customer_{order_id:04d}",
        "OrderDate": random_date(),
        "Items": {"Item": items},
        "TotalAmount": round(total, 2),
    }


def generate_1000_orders(xsd_path: Path, xml_path: Path, count: int = 1000) -> None:
    """Encode *count* orders via xmlschema and write to *xml_path*."""
    schema = xmlschema.XMLSchema(xsd_path.as_posix())

    orders_data = {"Order": [random_order(i + 1) for i in range(count)]}

    # xmlschema.encode returns an ElementTree Element
    xml_root = schema.encode(orders_data, path="Orders")

    xml_path.parent.mkdir(parents=True, exist_ok=True)
    tree = ET.ElementTree(xml_root)
    ET.indent(tree, space="  ")
    tree.write(xml_path.as_posix(), encoding="utf-8", xml_declaration=True)
    print(f"Generated {count} orders → {xml_path}")

    # Validate
    schema.validate(xml_path.as_posix())
    print("Validation successful.")


def main():
    data_home = os.environ.get("DATA_HOME", ".")
    xsd_path = Path(data_home) / "file_data" / "xml" / "orders.xsd"
    xml_path = Path(data_home) / "file_data" / "xml" / "orders.xml"

    # Ensure the XSD exists
    generate_xsd_file(xsd_path)

    generate_1000_orders(xsd_path, xml_path)


if __name__ == "__main__":
    main()
