WITH PARSED_DATA AS (
    SELECT
        JT.TOPIC_NAME,
        JT.PARTITION_ID,
        JT.PARTITION_OFFSET
    FROM
        KAFKA_OFFSET JD,
        JSON_TABLE(JD.DETAILS,
        '$.topics_arr[*]' COLUMNS ( TOPIC_NAME VARCHAR2(50) PATH '$.tp_nm',
        NESTED PATH '$.partitions[*]' COLUMNS ( PARTITION_ID VARCHAR2(10) PATH '$.id',
        PARTITION_OFFSET NUMBER PATH '$.offset' ) ) ) JT         
)
SELECT
    JSON_OBJECTAGG(KEY TOPIC_NAME VALUE JSON_OBJECTAGG(KEY PARTITION_ID VALUE CAST(PARTITION_OFFSET+1 AS INT) RETURNING VARCHAR2)) AS STARTING_OFFSETS,
    1 AS ID
FROM
    PARSED_DATA
GROUP BY
    TOPIC_NAME
UNION
SELECT
    '{"DOMAIN-DATA-MVNO-LINE-PROD": "LATEST"}' AS STARTING_OFFSETS,
    -1 AS ID
FROM
    DUAL