[project]
name = "spark-function"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "pyspark[pandas-on-spark]>=3.5.5",
    "python-dotenv>=1.0.1",
]
