[project]
name = "spark-xml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chardet>=5.2.0",
    "faker>=37.4.2",
    "generateds>=2.44.3",
    "lxml>=6.0.0",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "pyspark<4.0.0",
    "requests>=2.32.4",
    "xmlschema>=4.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8-pyproject>=1.2.3",
    "isort>=6.0.1",
]
