"""
Event-time is the time embedded in the data itself.
For many applications, you may want to operate on this event-time.
For example, if you want to get the number of events generated by IoT devices every minute, then you probably want to
use the time when the data was generated (that is, event-time in the data), rather than the time Spark receives them.
This event-time is very naturally expressed in this model – each event from the devices is a row in the table, and
event-time is a column value in the row.
This allows window-based aggregations (e.g. number of events every minute) to be just a special type of grouping and
aggregation on the event-time column – each time window is a group and each row can belong to multiple windows/groups.
Therefore, such event-time-window-based aggregation queries can be defined consistently on both a static dataset (e.g.
from collected device events logs) and on a data stream, making the life of the user much easier.
"""
if __name__ == '__main__':
    print()
