"""Mock OAuth2 assertion (RFC 7523 JWT-bearer) token endpoint + protected
resource, used to demo the `oauth2_assertion` authentication flow end to
end without hitting a real identity provider.

- `POST /token` validates the signed JWT assertion (RS256) against the
  public certificate generated by `generate_assertion_certs.sh`, checks the
  `aud` claim and expiry, then issues a short-lived bearer access token.
- `GET /students` requires that bearer token and returns a small dataset,
  matching the `result_key: "students"` used by
  `api_oauth2_assertion_etl.yaml`.

Run `generate_assertion_certs.sh` once before starting this server so the
public certificate used for signature verification exists under
`${DATA_HOME}/rest_api_ds/certs/assertion_client.pem`.
"""

import logging
import os
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import jwt
import uvicorn
from cryptography import x509
from fastapi import Depends, FastAPI, HTTPException, Request, status
from jwt import PyJWTError
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI()

DATA_HOME = os.environ.get("DATA_HOME", "/tmp")
CERTS_DIR = Path(DATA_HOME) / "rest_api_ds" / "certs"
PUBLIC_CERT_PATH = CERTS_DIR / "assertion_client.pem"

TOKEN_URL = "http://localhost:8081/token"
EXPECTED_AUD = TOKEN_URL
EXPECTED_GRANT_TYPE = "urn:ietf:params:oauth:grant-type:jwt-bearer"

# Internal token signing secret — only used to issue our own opaque bearer
# tokens once the client's assertion has been verified; unrelated to the
# RS256 assertion signing key.
ACCESS_TOKEN_SECRET = "mock-assertion-access-token-secret"  # nosec B105
ACCESS_TOKEN_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 15


class TokenRequest(BaseModel):
    grant_type: str
    assertion: str


class TokenResponse(BaseModel):
    access_token: str
    token_type: str


def _load_verification_public_key():
    if not PUBLIC_CERT_PATH.exists():
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=(
                f"Missing {PUBLIC_CERT_PATH}. Run generate_assertion_certs.sh "
                "before starting this mock server."
            ),
        )
    cert = x509.load_pem_x509_certificate(PUBLIC_CERT_PATH.read_bytes())
    return cert.public_key()


@app.post("/token", response_model=TokenResponse)
def issue_token(body: TokenRequest):
    if body.grant_type != EXPECTED_GRANT_TYPE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported grant_type: {body.grant_type}",
        )

    public_key = _load_verification_public_key()
    try:
        claims = jwt.decode(
            body.assertion,
            key=public_key,
            algorithms=["RS256"],
            audience=EXPECTED_AUD,
        )
    except PyJWTError as exc:
        logger.warning("Assertion verification failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid assertion: {exc}",
        )

    access_token = jwt.encode(
        {
            "sub": claims.get("jti", str(uuid.uuid4())),
            "exp": datetime.now(timezone.utc)
            + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES),
        },
        ACCESS_TOKEN_SECRET,
        algorithm=ACCESS_TOKEN_ALGORITHM,
    )
    return TokenResponse(access_token=access_token, token_type="bearer")


def _get_current_subject(request: Request) -> str:
    auth_header = request.headers.get("Authorization")
    if not auth_header or not auth_header.startswith("Bearer "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid Authorization header",
        )
    token = auth_header.split(" ", 1)[1]
    try:
        payload = jwt.decode(
            token, ACCESS_TOKEN_SECRET, algorithms=[ACCESS_TOKEN_ALGORITHM]
        )
    except PyJWTError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED, detail=f"Invalid token: {exc}"
        )
    return payload["sub"]


students_db = [
    {"id": 1, "name": "Alice", "major": "Computer Science"},
    {"id": 2, "name": "Bob", "major": "Mathematics"},
    {"id": 3, "name": "Charlie", "major": "Physics"},
]


@app.get("/students")
def get_students(subject: str = Depends(_get_current_subject)):
    return {"subject": subject, "students": students_db}


def main():
    uvicorn.run(app, host="localhost", port=8081, log_level="info")


if __name__ == "__main__":
    main()
