apiVersion: v1
kind: Service
metadata:
  name: "mysql"
  labels:
    app: "mysql-app"
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31306
  selector:
    app: "mysql-app"